# Generated by Django 5.2.2 on 2025-06-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('usuario', 'Usuario '), ('sistemas', 'Sistemas')], default='usuario', max_length=20),
        ),
    ]
