# Generated by Django 5.2.2 on 2025-06-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_ticket_imagenticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='categoria_sistemas',
            field=models.CharField(blank=True, choices=[('soporte_tecnico', 'Soporte Técnico'), ('infraestructura', 'Infraestructura'), ('desarrollo', 'Desarrollo')], max_length=20, null=True),
        ),
    ]
