# Generated by Django 5.2.2 on 2025-06-19 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuario_categoria_sistemas'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='asignado_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_asignados', to='usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_creados', to='usuarios.usuario'),
        ),
    ]
