# Generated by Django 5.2.2 on 2025-06-25 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_ticket_asignado_a_alter_ticket_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='nivel_urgencia',
            field=models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=10),
        ),
    ]
