# Generated by Django 5.2.2 on 2025-06-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_ticket_nivel_urgencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='estatus',
            field=models.CharField(choices=[('abierto', 'Abierto'), ('en_progreso', 'En Progreso'), ('esperando_respuesta', 'Esperando Respuesta'), ('resuelto', 'Resuelto'), ('cerrado', 'Cerrado')], default='abierto', max_length=20),
        ),
    ]
