# Generated by Django 5.2.2 on 2025-06-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_ticket_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='estatus',
            field=models.CharField(choices=[('generado', 'Generado'), ('en_proceso', 'En Proceso'), ('cancelado', 'Cancelado'), ('en_espera', 'En espera'), ('finalizado', 'Finalizado')], default='generado', max_length=20),
        ),
    ]
