# Generated by Django 5.2.2 on 2025-07-02 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_ticket_estatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteFinalizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('reporte', models.TextField()),
                ('descripcion', models.TextField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reporte_finalizacion', to='usuarios.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='reportes/')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='usuarios.reportefinalizacion')),
            ],
        ),
    ]
