# Generated by Django 5.2.2 on 2025-07-02 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_reportefinalizacion_imagenreporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportefinalizacion',
            name='visto_por_usuario',
            field=models.BooleanField(default=False),
        ),
    ]
