# Generated by Django 5.2.2 on 2025-07-06 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_reportefinalizacion_visto_por_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenreporte',
            name='imagen',
            field=models.ImageField(upload_to='reportes/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='imagenticket',
            name='imagen',
            field=models.ImageField(upload_to='tickets/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('usuario', 'Usuario'), ('sistemas', 'Sistemas')], default='usuario', max_length=20),
        ),
    ]
