# Generated by Django 5.2.2 on 2025-07-08 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_alter_imagenreporte_imagen_alter_imagenticket_imagen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelacionTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('fecha_cancelacion', models.DateTimeField(auto_now_add=True)),
                ('cancelado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cancelacion', to='usuarios.ticket')),
            ],
        ),
    ]
