# Generated by Django 5.2.2 on 2025-07-09 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_cancelacionticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoEspera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='motivo_espera', to='usuarios.ticket')),
            ],
        ),
    ]
