# Generated by Django 5.2.2 on 2025-07-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_motivoespera'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='asignado_por_admin',
            field=models.BooleanField(default=False),
        ),
    ]
