# Generated by Django 5.2.2 on 2025-07-25 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_usuario_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='admitido',
            field=models.BooleanField(default=False),
        ),
    ]
