# Generated by Django - Migración de urgencias para app 'usuarios'

from django.db import migrations

def convertir_urgencias_texto_a_numero(apps, schema_editor):
    """Convierte urgencias de texto ('baja', 'media') a números (1, 2, 3, 4)"""
    
    # 🔧 CORREGIDO: Obtener el modelo Ticket de la app 'usuarios'
    Ticket = apps.get_model('usuarios', 'Ticket')
    
    # Mapa de conversión
    conversiones = {
        'baja': 1,
        'media': 2,
        'alta': 3,
        'critica': 4,
        'crítica': 4,
        # Por si ya hay algunos números como string
        '1': 1,
        '2': 2, 
        '3': 3,
        '4': 4,
    }
    
    # Contar tickets para mostrar progreso
    total_tickets = Ticket.objects.count()
    convertidos = 0
    
    print(f"🔄 Iniciando conversión de {total_tickets} tickets...")
    
    # Convertir todos los tickets
    for ticket in Ticket.objects.all():
        urgencia_original = ticket.nivel_urgencia
        
        # Convertir a string y lowercase para comparar
        urgencia_str = str(urgencia_original).lower().strip()
        
        if urgencia_str in conversiones:
            nuevo_valor = conversiones[urgencia_str]
            ticket.nivel_urgencia = nuevo_valor
            ticket.save()
            convertidos += 1
            print(f"✅ Ticket {ticket.id}: '{urgencia_original}' → {nuevo_valor}")
        else:
            print(f"⚠️  Ticket {ticket.id}: Urgencia no reconocida '{urgencia_original}'")
    
    print(f"🎉 Conversión completada: {convertidos}/{total_tickets} tickets convertidos")

def revertir_urgencias_numero_a_texto(apps, schema_editor):
    """Revierte la conversión (por si necesitas volver atrás)"""
    
    # 🔧 CORREGIDO: Obtener el modelo Ticket de la app 'usuarios'
    Ticket = apps.get_model('usuarios', 'Ticket')
    
    # Mapa de reversión
    reversiones = {
        1: 'baja',
        2: 'media',
        3: 'alta', 
        4: 'critica',
    }
    
    total_tickets = Ticket.objects.count()
    revertidos = 0
    
    print(f"🔄 Revirtiendo {total_tickets} tickets...")
    
    for ticket in Ticket.objects.all():
        urgencia_original = ticket.nivel_urgencia
        
        try:
            urgencia_num = int(urgencia_original)
            if urgencia_num in reversiones:
                nuevo_valor = reversiones[urgencia_num]
                ticket.nivel_urgencia = nuevo_valor
                ticket.save()
                revertidos += 1
                print(f"↩️  Ticket {ticket.id}: {urgencia_original} → '{nuevo_valor}'")
        except (ValueError, TypeError):
            print(f"⚠️  Ticket {ticket.id}: No se pudo revertir '{urgencia_original}'")
    
    print(f"🎉 Reversión completada: {revertidos}/{total_tickets} tickets revertidos")

class Migration(migrations.Migration):

    dependencies = [
        # 🔧 CORREGIDO: Usar la app 'usuarios' y tu última migración
        ('usuarios', '0017_usuario_foto_perfil'),
    ]

    operations = [
        migrations.RunPython(
            convertir_urgencias_texto_a_numero,
            reverse_code=revertir_urgencias_numero_a_texto,
        ),
    ]