# Generated by Django 5.2.2 on 2025-07-26 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0018_convertir_urgencias_a_numeros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='nivel_urgencia',
            field=models.IntegerField(choices=[(1, 'Baja'), (2, 'Media'), (3, 'Alta'), (4, 'Crítica')], default=2),
        ),
    ]
